### ISSUE TITLE
[Pods strange behaviour] Pods status switching between running, error and CrashLoopBackOff

### ISSUE THREAD

**Issue by caohch-1** [Cloud-and-Distributed-Systems/Erms#3]
After I deploy the hotel-reserv service, I find that the pods behaviour is strange. Following is the status history of pods in hotel-reserv:
```bash
caohch1@caohch1-OptiPlex-7090:~/Desktop$ kubectl get pods -n hotel-reserv -w
NAME                                      READY   STATUS    RESTARTS     AGE
consul-7d9cb8d-ws4wh                      1/1     Running   0            45s
frontend-5bd6586dcc-lzl9n                 1/1     Running   0            19s
geo-7d75ddf4f8-k2k5c                      1/1     Running   1 (7s ago)   19s
jaeger-5f7578ffbb-8sxt6                   1/1     Running   0            44s
memcached-profile-687fb5bb67-9srn7        1/1     Running   0            45s
memcached-rate-649c88cfcc-8l899           1/1     Running   0            45s
memcached-reserve-76f4ff88f-2ss9p         1/1     Running   0            44s
mongodb-geo-66d5c5f54b-zl6xg              1/1     Running   0            45s
mongodb-profile-5878776f4d-p2hrr          1/1     Running   0            45s
mongodb-rate-77c6f496c5-6bgnq             1/1     Running   0            45s
mongodb-recommendation-7c76c9d4bd-x9j62   1/1     Running   0            45s
mongodb-reservation-6c4c6f5cc6-8whxm      1/1     Running   0            45s
mongodb-user-66f857bd96-c24bg             1/1     Running   0            45s
profile-6696d456-mq5qw                    1/1     Running   1 (7s ago)   19s
rate-78c484d456-4knd4                     1/1     Running   1 (7s ago)   20s
recommendation-677c858468-plgbr           1/1     Running   1 (7s ago)   20s
reservation-6c47d856cf-rm7bv              1/1     Running   1 (7s ago)   19s
search-6459f7899b-gr5cg                   1/1     Running   0            19s
user-697d995867-pdzxh                     1/1     Running   1 (7s ago)   19s
profile-6696d456-mq5qw                    0/1     Error     1 (13s ago)   25s
recommendation-677c858468-plgbr           0/1     Error     1 (13s ago)   26s
user-697d995867-pdzxh                     0/1     Error     1 (13s ago)   25s
geo-7d75ddf4f8-k2k5c                      0/1     Error     1 (13s ago)   25s
rate-78c484d456-4knd4                     0/1     Error     1 (13s ago)   26s
reservation-6c47d856cf-rm7bv              0/1     Error     1 (13s ago)   25s
recommendation-677c858468-plgbr           0/1     CrashLoopBackOff   1 (12s ago)   38s
profile-6696d456-mq5qw                    0/1     CrashLoopBackOff   1 (12s ago)   37s
profile-6696d456-mq5qw                    1/1     Running            2 (12s ago)   37s
recommendation-677c858468-plgbr           1/1     Running            2 (12s ago)   38s
user-697d995867-pdzxh                     0/1     CrashLoopBackOff   1 (14s ago)   39s
rate-78c484d456-4knd4                     0/1     CrashLoopBackOff   1 (14s ago)   40s
reservation-6c47d856cf-rm7bv              0/1     CrashLoopBackOff   1 (14s ago)   39s
user-697d995867-pdzxh                     1/1     Running            2 (14s ago)   39s
rate-78c484d456-4knd4                     1/1     Running            2 (14s ago)   40s
reservation-6c47d856cf-rm7bv              1/1     Running            2 (14s ago)   39s
geo-7d75ddf4f8-k2k5c                      0/1     CrashLoopBackOff   1 (15s ago)   40s
geo-7d75ddf4f8-k2k5c                      1/1     Running            2             40s
profile-6696d456-mq5qw                    0/1     Error              2 (25s ago)   50s
recommendation-677c858468-plgbr           0/1     Error              2 (25s ago)   51s
rate-78c484d456-4knd4                     0/1     Error              2 (26s ago)   52s
reservation-6c47d856cf-rm7bv              0/1     Error              2 (26s ago)   51s
user-697d995867-pdzxh                     0/1     Error              2 (26s ago)   51s
geo-7d75ddf4f8-k2k5c                      0/1     Error              2             53s
recommendation-677c858468-plgbr           0/1     CrashLoopBackOff   2 (13s ago)   63s
profile-6696d456-mq5qw                    0/1     CrashLoopBackOff   2 (14s ago)   63s
geo-7d75ddf4f8-k2k5c                      0/1     CrashLoopBackOff   2 (11s ago)   63s
user-697d995867-pdzxh                     0/1     CrashLoopBackOff   2 (14s ago)   64s
reservation-6c47d856cf-rm7bv              0/1     CrashLoopBackOff   2 (15s ago)   65s
rate-78c484d456-4knd4                     0/1     CrashLoopBackOff   2 (16s ago)   67s
recommendation-677c858468-plgbr           1/1     Running            3 (25s ago)   75s
user-697d995867-pdzxh                     1/1     Running            3 (27s ago)   77s
profile-6696d456-mq5qw                    1/1     Running            3 (29s ago)   78s
reservation-6c47d856cf-rm7bv              1/1     Running            3 (28s ago)   78s
rate-78c484d456-4knd4                     1/1     Running            3 (28s ago)   79s
geo-7d75ddf4f8-k2k5c                      1/1     Running            3 (27s ago)   79s
recommendation-677c858468-plgbr           0/1     Error              3 (37s ago)   87s
profile-6696d456-mq5qw                    0/1     Error              3 (40s ago)   89s
user-697d995867-pdzxh                     0/1     Error              3 (39s ago)   89s
geo-7d75ddf4f8-k2k5c                      0/1     Error              3 (38s ago)   90s
rate-78c484d456-4knd4                     0/1     Error              3 (40s ago)   91s
reservation-6c47d856cf-rm7bv              0/1     Error              3 (40s ago)   90s
recommendation-677c858468-plgbr           0/1     CrashLoopBackOff   3 (11s ago)   98s
profile-6696d456-mq5qw                    0/1     CrashLoopBackOff   3 (11s ago)   100s
reservation-6c47d856cf-rm7bv              0/1     CrashLoopBackOff   3 (13s ago)   102s
user-697d995867-pdzxh                     0/1     CrashLoopBackOff   3 (16s ago)   104s
rate-78c484d456-4knd4                     0/1     CrashLoopBackOff   3 (15s ago)   105s
geo-7d75ddf4f8-k2k5c                      0/1     CrashLoopBackOff   3 (14s ago)   104s
user-697d995867-pdzxh                     1/1     Running            4 (43s ago)   2m11s
reservation-6c47d856cf-rm7bv              1/1     Running            4 (42s ago)   2m11s
rate-78c484d456-4knd4                     1/1     Running            4 (45s ago)   2m15s
recommendation-677c858468-plgbr           1/1     Running            4 (50s ago)   2m17s
user-697d995867-pdzxh                     0/1     Error              4 (54s ago)   2m22s
reservation-6c47d856cf-rm7bv              0/1     Error              4 (53s ago)   2m22s
profile-6696d456-mq5qw                    1/1     Running            4 (53s ago)   2m22s
geo-7d75ddf4f8-k2k5c                      1/1     Running            4 (53s ago)   2m23s
rate-78c484d456-4knd4                     0/1     Error              4 (56s ago)   2m26s
recommendation-677c858468-plgbr           0/1     Error              4 (61s ago)   2m28s
user-697d995867-pdzxh                     0/1     CrashLoopBackOff   4 (12s ago)   2m33s
profile-6696d456-mq5qw                    0/1     Error              4 (66s ago)   2m35s
geo-7d75ddf4f8-k2k5c                      0/1     Error              4 (65s ago)   2m35s
reservation-6c47d856cf-rm7bv              0/1     CrashLoopBackOff   4 (15s ago)   2m36s
recommendation-677c858468-plgbr           0/1     CrashLoopBackOff   4 (13s ago)   2m40s
rate-78c484d456-4knd4                     0/1     CrashLoopBackOff   4 (16s ago)   2m41s
geo-7d75ddf4f8-k2k5c                      0/1     CrashLoopBackOff   4 (11s ago)   2m45s
profile-6696d456-mq5qw                    0/1     CrashLoopBackOff   4 (12s ago)   2m46s
user-697d995867-pdzxh                     1/1     Running            5 (83s ago)   3m44s
reservation-6c47d856cf-rm7bv              1/1     Running            5 (90s ago)   3m51s
rate-78c484d456-4knd4                     1/1     Running            5 (87s ago)   3m52s
recommendation-677c858468-plgbr           1/1     Running            5 (90s ago)   3m57s
user-697d995867-pdzxh                     0/1     Error              5 (95s ago)   3m56s
geo-7d75ddf4f8-k2k5c                      1/1     Running            5 (83s ago)   3m57s
profile-6696d456-mq5qw                    1/1     Running            5 (84s ago)   3m58s
rate-78c484d456-4knd4                     0/1     Error              5 (99s ago)   4m4s
reservation-6c47d856cf-rm7bv              0/1     Error              5 (102s ago)   4m3s
recommendation-677c858468-plgbr           0/1     Error              5 (102s ago)   4m9s
geo-7d75ddf4f8-k2k5c                      0/1     Error              5 (96s ago)    4m10s
profile-6696d456-mq5qw                    0/1     Error              5 (97s ago)    4m11s
user-697d995867-pdzxh                     0/1     CrashLoopBackOff   5 (17s ago)    4m12s
rate-78c484d456-4knd4                     0/1     CrashLoopBackOff   5 (16s ago)    4m19s
reservation-6c47d856cf-rm7bv              0/1     CrashLoopBackOff   5 (16s ago)    4m18s
recommendation-677c858468-plgbr           0/1     CrashLoopBackOff   5 (13s ago)    4m21s
geo-7d75ddf4f8-k2k5c                      0/1     CrashLoopBackOff   5 (13s ago)    4m22s
profile-6696d456-mq5qw                    0/1     CrashLoopBackOff   5 (13s ago)    4m23s
...
```
The status of pods switching between normal and panic and I find that they finally stay in status of `CrashLoopBackOff`. I check these pods and following is the error logs,:
```bash
caohch1@caohch1-OptiPlex-7090:~/Desktop$ kubectl logs geo-7d75ddf4f8-k2k5c -n hotel-reserv
2023/03/10 06:45:25 TLS disabled
2023-03-10T06:45:25Z INF cmd/geo/main.go:21 > Reading config...
2023-03-10T06:45:25Z INF cmd/geo/main.go:34 > Read database URL: mongodb-geo:27017
2023-03-10T06:45:25Z INF cmd/geo/main.go:35 > Initializing DB connection...
2023-03-10T06:45:37Z PNC cmd/geo/db.go:20 > no reachable servers
panic: no reachable servers

goroutine 1 [running]:
github.com/rs/zerolog.(*Logger).Panic.func1({0x96aba8, 0x0})
	/go/src/github.com/harlow/go-micro-services/vendor/github.com/rs/zerolog/log.go:359 +0x2d
github.com/rs/zerolog.(*Event).msg(0xc000218480, {0x96aba8, 0x14})
	/go/src/github.com/harlow/go-micro-services/vendor/github.com/rs/zerolog/event.go:149 +0x2b8
github.com/rs/zerolog.(*Event).Msg(...)
	/go/src/github.com/harlow/go-micro-services/vendor/github.com/rs/zerolog/event.go:108
main.initializeDatabase({0xc0000d4168, 0xc0000a9c20})
	/go/src/github.com/harlow/go-micro-services/cmd/geo/db.go:20 +0xa5
main.main()
	/go/src/github.com/harlow/go-micro-services/cmd/geo/main.go:36 +0x728
```
It seems that some module in the microservice try to connect to the database but failed. Does it have something to do with the version of mongodb image version or some configurations that I might miss?

**Comment by Nick-LCY** [comment]
In my experience, this is because you have too many pods. `HotelReservation` uses consul for service discovery, but when there are too many pods, it often crashes and causes abnormal tail latency. For `HotelReservation`, I suggest you experiment with a small number of pods.

**Comment by caohch-1** [comment]
I start a new cluster and replace the official image from docker-hub with yours (i.e., nicklin9907/erms) and it works well!
